services:
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M

  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DEV: "false"
    expose:
      - "8000"
    volumes:
      - log_volume:/vol/web/logs
      - static_volume:/vol/web/static
      - media_volume:/vol/web/media
    environment:
      - DEBUG=false
      - SECRET_KEY=${SECRET_KEY}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=db
      - DB_PORT=5432
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - STATIC_ROOT=${STATIC_ROOT}
      - MEDIA_ROOT=${MEDIA_ROOT}
      - DJANGO_SUPERUSER_USERNAME=${DJANGO_SUPERUSER_USERNAME}
      - DJANGO_SUPERUSER_EMAIL=${DJANGO_SUPERUSER_EMAIL}
      - DJANGO_SUPERUSER_PASSWORD=${DJANGO_SUPERUSER_PASSWORD}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 2G
        reservations:
          cpus: '1.0'
          memory: 1G
    networks:
      - default
      - web
    labels:
      - "traefik.enable=true"
      # Crucial: Must match the network name below and in your Traefik container
      - "traefik.docker.network=web"
      
      # 1. HTTP ROUTER (Port 80)
      - "traefik.http.routers.seaf.entrypoints=web"
      - "traefik.http.routers.seaf.rule=Host(`seaf.cenariodigital.dev`)"
      
      # 2. HTTPS REDIRECT MIDDLEWARE
      - "traefik.http.middlewares.seaf-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.seaf.middlewares=seaf-https-redirect"
      
      # 3. HTTPS ROUTER (Port 443)
      - "traefik.http.routers.seaf-secure.entrypoints=websecure"
      - "traefik.http.routers.seaf-secure.rule=Host(`seaf.cenariodigital.dev`)"
      - "traefik.http.routers.seaf-secure.tls=true"
      - "traefik.http.routers.seaf-secure.tls.certresolver=cloudflare"
      
      # 4. SERVICE DEFINITION
      - "traefik.http.routers.seaf-secure.service=seaf"
      - "traefik.http.services.seaf.loadbalancer.server.port=8000"


volumes:
  postgres_data:
  log_volume:
  static_volume:
  media_volume:

networks:
  web:
    external: true