# Generated by Django 5.2.7 on 2025-11-14 01:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('custom_auth', '0001_initial'),
    ]

    operations = [
        # Remove old custom group models
        migrations.DeleteModel(
            name='UserGroup',
        ),
        migrations.DeleteModel(
            name='GroupPermission',
        ),
        migrations.DeleteModel(
            name='PermissionGroup',
        ),
        # Create new model linking Django's Group to ResourcePermission
        migrations.CreateModel(
            name='GroupResourcePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_permissions', to='auth.group')),
                ('resource_permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='custom_auth.resourcepermission')),
            ],
            options={
                'verbose_name': 'Group-Permission Assignment',
                'verbose_name_plural': 'Group-Permission Assignments',
                'db_table': 'auth_group_resource_permission',
                'unique_together': {('group', 'resource_permission')},
            },
        ),
    ]
