# Generated by Django 5.2.7 on 2025-11-25 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('cities', '0008_municipality_seaf_category'),
        ('custom_auth', '0002_remove_custom_groups'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='groupresourcepermission',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='groupresourcepermission',
            name='region',
            field=models.ForeignKey(blank=True, help_text='If set, permission applies only to this region. If null, applies to all regions.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_permissions', to='cities.region'),
        ),
        migrations.AlterUniqueTogether(
            name='groupresourcepermission',
            unique_together={('group', 'resource_permission', 'region')},
        ),
    ]
