# Generated by Django 5.2.7 on 2025-10-28 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IntermediateRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=4, unique=True, verbose_name='Region Code')),
                ('name', models.CharField(max_length=200, verbose_name='Region Name')),
            ],
            options={
                'verbose_name': 'Intermediate Region',
                'verbose_name_plural': 'Intermediate Regions',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=2, unique=True, verbose_name='State Code')),
                ('name', models.CharField(max_length=100, verbose_name='State Name')),
            ],
            options={
                'verbose_name': 'State',
                'verbose_name_plural': 'States',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ImmediateRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6, unique=True, verbose_name='Region Code')),
                ('name', models.CharField(max_length=200, verbose_name='Region Name')),
                ('intermediate_region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='immediate_regions', to='cities.intermediateregion')),
            ],
            options={
                'verbose_name': 'Immediate Region',
                'verbose_name_plural': 'Immediate Regions',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='intermediateregion',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intermediate_regions', to='cities.state'),
        ),
        migrations.CreateModel(
            name='Municipality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=7, unique=True, verbose_name='Municipality Code')),
                ('name', models.CharField(max_length=200, verbose_name='Municipality Name')),
                ('immediate_region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='municipalities', to='cities.immediateregion')),
            ],
            options={
                'verbose_name': 'Municipality',
                'verbose_name_plural': 'Municipalities',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['code'], name='cities_muni_code_20568f_idx'), models.Index(fields=['name'], name='cities_muni_name_e6406f_idx')],
            },
        ),
    ]
