# Generated by Django 5.2.7 on 2025-10-29 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='state',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='Longitude'),
        ),
        migrations.AddField(
            model_name='state',
            name='regiao',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Região'),
        ),
    ]
