# Generated by Django 5.2.7 on 2025-10-29 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0002_state_latitude_state_longitude_state_regiao'),
    ]

    operations = [
        migrations.AddField(
            model_name='municipality',
            name='area_code',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='Area Code (DDD)'),
        ),
        migrations.AddField(
            model_name='municipality',
            name='is_capital',
            field=models.BooleanField(default=False, verbose_name='Is Capital'),
        ),
        migrations.AddField(
            model_name='municipality',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='municipality',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='Longitude'),
        ),
        migrations.AddField(
            model_name='municipality',
            name='siafi_id',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='SIAFI ID'),
        ),
        migrations.AddField(
            model_name='municipality',
            name='timezone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Timezone'),
        ),
    ]
