# Generated by Django 5.2.7 on 2025-10-29 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0003_municipality_area_code_municipality_is_capital_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='abbreviation',
            field=models.CharField(blank=True, max_length=2, null=True, unique=True, verbose_name='State Abbreviation'),
        ),
    ]
