# Generated by Django 5.2.7 on 2025-10-29 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0004_state_abbreviation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=2, unique=True, verbose_name='Region Code')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Region Name')),
            ],
            options={
                'verbose_name': 'Region',
                'verbose_name_plural': 'Regions',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='state',
            name='regiao',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Região (deprecated)'),
        ),
        migrations.AddField(
            model_name='state',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='states', to='cities.region', verbose_name='Region'),
        ),
    ]
