# Generated by Django 5.2.7 on 2025-10-30 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0005_region_alter_state_regiao_state_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='municipality',
            name='mayor_data_updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Mayor Data Updated At'),
        ),
        migrations.AddField(
            model_name='municipality',
            name='mayor_mandate_end',
            field=models.IntegerField(blank=True, null=True, verbose_name='Mandate End Year'),
        ),
        migrations.AddField(
            model_name='municipality',
            name='mayor_mandate_start',
            field=models.IntegerField(blank=True, null=True, verbose_name='Mandate Start Year'),
        ),
        migrations.AddField(
            model_name='municipality',
            name='mayor_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Mayor Name'),
        ),
        migrations.AddField(
            model_name='municipality',
            name='mayor_party',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Mayor Party'),
        ),
        migrations.AddField(
            model_name='municipality',
            name='wikipedia_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Wikipedia URL'),
        ),
    ]
