# Generated by Django 5.2.7 on 2025-11-10 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0006_municipality_mayor_data_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='municipality',
            name='wiki_altitude',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Altitude (Wikipedia)'),
        ),
        migrations.AddField(
            model_name='municipality',
            name='wiki_bordering_municipalities',
            field=models.TextField(blank=True, null=True, verbose_name='Bordering Municipalities (Wikipedia)'),
        ),
        migrations.AddField(
            model_name='municipality',
            name='wiki_climate',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Climate (Wikipedia)'),
        ),
        migrations.AddField(
            model_name='municipality',
            name='wiki_council_members',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Council Members (Wikipedia)'),
        ),
        migrations.AddField(
            model_name='municipality',
            name='wiki_data_updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Wikipedia Data Updated At'),
        ),
        migrations.AddField(
            model_name='municipality',
            name='wiki_demonym',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Demonym (Wikipedia)'),
        ),
        migrations.AddField(
            model_name='municipality',
            name='wiki_density',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Density (Wikipedia)'),
        ),
        migrations.AddField(
            model_name='municipality',
            name='wiki_distance_to_capital',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Distance to Capital (Wikipedia)'),
        ),
        migrations.AddField(
            model_name='municipality',
            name='wiki_foundation_date',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Foundation Date (Wikipedia)'),
        ),
        migrations.AddField(
            model_name='municipality',
            name='wiki_gdp',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='GDP (Wikipedia)'),
        ),
        migrations.AddField(
            model_name='municipality',
            name='wiki_gdp_per_capita',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='GDP Per Capita (Wikipedia)'),
        ),
        migrations.AddField(
            model_name='municipality',
            name='wiki_gini',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Gini Coefficient (Wikipedia)'),
        ),
        migrations.AddField(
            model_name='municipality',
            name='wiki_idh',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='IDH (Wikipedia)'),
        ),
        migrations.AddField(
            model_name='municipality',
            name='wiki_mayor_mandate_end',
            field=models.IntegerField(blank=True, null=True, verbose_name='Mayor Mandate End (Wikipedia)'),
        ),
        migrations.AddField(
            model_name='municipality',
            name='wiki_mayor_mandate_start',
            field=models.IntegerField(blank=True, null=True, verbose_name='Mayor Mandate Start (Wikipedia)'),
        ),
        migrations.AddField(
            model_name='municipality',
            name='wiki_mayor_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Mayor Name (Wikipedia)'),
        ),
        migrations.AddField(
            model_name='municipality',
            name='wiki_mayor_party',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Mayor Party (Wikipedia)'),
        ),
        migrations.AddField(
            model_name='municipality',
            name='wiki_metropolitan_region',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Metropolitan Region (Wikipedia)'),
        ),
        migrations.AddField(
            model_name='municipality',
            name='wiki_population',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Population (Wikipedia)'),
        ),
        migrations.AddField(
            model_name='municipality',
            name='wiki_postal_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Postal Code (Wikipedia)'),
        ),
        migrations.AddField(
            model_name='municipality',
            name='wiki_total_area',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Total Area (Wikipedia)'),
        ),
        migrations.AddField(
            model_name='municipality',
            name='wiki_website',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Website (Wikipedia)'),
        ),
    ]
