# Generated by Django 5.2.7 on 2025-11-12 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0007_municipality_wiki_altitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='municipality',
            name='seaf_category',
            field=models.IntegerField(blank=True, null=True, verbose_name='SEAF Category'),
        ),
    ]
