# Generated by Django 5.2.7 on 2025-11-17 17:42

from django.db import migrations


def copy_wiki_mayor_to_mayor(apps, schema_editor):
    """Copy data from wiki_mayor_name and wiki_mayor_party to mayor_name and mayor_party"""
    Municipality = apps.get_model('cities', 'Municipality')
    
    # Update all municipalities
    municipalities = Municipality.objects.all()
    for municipality in municipalities:
        if municipality.wiki_mayor_name:
            municipality.mayor_name = municipality.wiki_mayor_name
        if municipality.wiki_mayor_party:
            municipality.mayor_party = municipality.wiki_mayor_party
    
    # Bulk update for efficiency
    Municipality.objects.bulk_update(municipalities, ['mayor_name', 'mayor_party'], batch_size=1000)


def reverse_copy(apps, schema_editor):
    """Reverse operation - copy back from mayor fields to wiki fields"""
    Municipality = apps.get_model('cities', 'Municipality')
    
    municipalities = Municipality.objects.all()
    for municipality in municipalities:
        if municipality.mayor_name:
            municipality.wiki_mayor_name = municipality.mayor_name
        if municipality.mayor_party:
            municipality.wiki_mayor_party = municipality.mayor_party
    
    Municipality.objects.bulk_update(municipalities, ['wiki_mayor_name', 'wiki_mayor_party'], batch_size=1000)


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0008_municipality_seaf_category'),
    ]

    operations = [
        migrations.RunPython(copy_wiki_mayor_to_mayor, reverse_copy),
    ]
