# Generated by Django 5.2.7 on 2025-11-17 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0009_copy_wiki_mayor_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='municipality',
            name='wiki_mayor_name',
        ),
        migrations.RemoveField(
            model_name='municipality',
            name='wiki_mayor_party',
        ),
    ]
