# Generated by Django 5.2.7 on 2025-11-17 20:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0010_remove_municipality_wiki_mayor_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MunicipalityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50, verbose_name='Ação')),
                ('field_name', models.CharField(blank=True, max_length=100, verbose_name='Campo')),
                ('old_value', models.TextField(blank=True, verbose_name='Valor Anterior')),
                ('new_value', models.TextField(blank=True, verbose_name='Valor Novo')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data/Hora')),
                ('municipality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_logs', to='cities.municipality', verbose_name='Município')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Log de Alteração de Município',
                'verbose_name_plural': 'Logs de Alterações de Municípios',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['municipality', '-created_at'], name='cities_muni_municip_58ee93_idx'), models.Index(fields=['user', '-created_at'], name='cities_muni_user_id_c47028_idx')],
            },
        ),
    ]
