# Generated by Django 5.2.7 on 2025-11-25 20:07

from django.db import migrations


def increment_seaf_categories(apps, schema_editor):
    """
    This function is responsible for incrementing all existing seaf_category values by 1
    to adjust from the old range (0-3) to the new range (1-4).
    """
    Municipality = apps.get_model('cities', 'Municipality')
    
    # Update all municipalities with seaf_category values
    municipalities = Municipality.objects.filter(seaf_category__isnull=False)
    for municipality in municipalities:
        municipality.seaf_category += 1
        municipality.save(update_fields=['seaf_category'])


def decrement_seaf_categories(apps, schema_editor):
    """
    This function is responsible for reverting seaf_category values back to the old range
    in case of migration rollback.
    """
    Municipality = apps.get_model('cities', 'Municipality')
    
    # Revert all municipalities with seaf_category values
    municipalities = Municipality.objects.filter(seaf_category__isnull=False)
    for municipality in municipalities:
        municipality.seaf_category -= 1
        municipality.save(update_fields=['seaf_category'])


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0011_municipalitylog'),
    ]

    operations = [
        migrations.RunPython(increment_seaf_categories, decrement_seaf_categories),
    ]
